POST http://0.0.0.0:8080/snippets
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoidGVzdDIifQ.PDbxXaa5V31OxJ4aafzvpu56cnJUF4zBn_lXzQpe1Ng

{
  "snippet": {
    "text": "aaaa"
  }
}

###
GET http://0.0.0.0:8080/snippets
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoidGVzdDIifQ.PDbxXaa5V31OxJ4aafzvpu56cnJUF4zBn_lXzQpe1Ng

###
POST http://0.0.0.0:8080/login
Content-Type: application/json

{
  "name": "test2",
  "phoneNum": "18628393484",
  "password": "test2"
}

###
POST http://0.0.0.0:8080/register
Content-Type: application/json

{
  "name": "test2",
  "phoneNum": "18628393484",
  "password": "test2"
}

